name: Create GitHub Release with Changelog

on:
  workflow_call:
    inputs:
      tag:
        required: true
        type: string
      changelog:
        required: true
        type: string
      python_dist:
        required: false
        type: string
      vsix:
        required: false
        type: string

jobs:
  github-release:
    if: github.actor == 'faelmori'
    runs-on: ubuntu-latest
    steps:
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ inputs.tag }}
          name: Release ${{ inputs.tag }}
          body: ${{ inputs.changelog }}
          files: |
            ${{ inputs.python_dist }}
            ${{ inputs.vsix }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
